[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      to = "websecure"
      scheme = "https"


  [entryPoints.websecure]
    address = ":443"


[accessLog]


[providers]
  [providers.docker]
    exposedByDefault = false


[certificatesResolvers.letsencrypt.acme]
  email = "wenrich85@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"
